//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Collections.Generic;
    
    public partial class ToolCabinetEntities : DbContext
    {
        public ToolCabinetEntities()
            : base("name=ToolCabinetEntities")
        {
        }
    
    	public ToolCabinetEntities(string connectionName)
            : base(connectionName)
        {
    
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tool> Tools { get; set; }
        public virtual DbSet<ToolRecord> ToolRecords { get; set; }
        public virtual DbSet<ToolType> ToolTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
