//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool : ObservableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tool()
        {
            this.ToolName = "";
            this.ToolBarCode = "";
            this.ToolRFIDCode = "";
            this.Status = false;
            this.Factory = "";
            this.Note = "";
            this.ToolRecords = new List<ToolRecord>();
        }
    
    	private int _id; //private字段
        public int id { get => _id; set => Set(ref _id, value); }
    
    	private string _ToolName; //private字段
        public string ToolName { get => _ToolName; set => Set(ref _ToolName, value); }
    
    	private int _ToolTypeId; //private字段
        public int ToolTypeId { get => _ToolTypeId; set => Set(ref _ToolTypeId, value); }
    
    	private string _ToolBarCode; //private字段
        public string ToolBarCode { get => _ToolBarCode; set => Set(ref _ToolBarCode, value); }
    
    	private string _ToolRFIDCode; //private字段
        public string ToolRFIDCode { get => _ToolRFIDCode; set => Set(ref _ToolRFIDCode, value); }
    
    	private int _Position; //private字段
        public int Position { get => _Position; set => Set(ref _Position, value); }
    
    	private bool _Status; //private字段
        public bool Status { get => _Status; set => Set(ref _Status, value); }
    
    	private System.DateTime _CreateDateTime; //private字段
        public System.DateTime CreateDateTime { get => _CreateDateTime; set => Set(ref _CreateDateTime, value); }
    
    	private decimal _RangeMin; //private字段
        public decimal RangeMin { get => _RangeMin; set => Set(ref _RangeMin, value); }
    
    	private decimal _RangeMax; //private字段
        public decimal RangeMax { get => _RangeMax; set => Set(ref _RangeMax, value); }
    
    	private string _Factory; //private字段
        public string Factory { get => _Factory; set => Set(ref _Factory, value); }
    
    	private string _Note; //private字段
        public string Note { get => _Note; set => Set(ref _Note, value); }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolRecord> ToolRecords { get; set; }
        public virtual ToolType ToolType { get; set; }
    }
}
