//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolRecord : ObservableObject
    {
    	private int _Id; //private字段
        public int Id { get => _Id; set => Set(ref _Id, value); }
    
    	private int _ToolId; //private字段
        public int ToolId { get => _ToolId; set => Set(ref _ToolId, value); }
    
    	private int _UserId; //private字段
        public int UserId { get => _UserId; set => Set(ref _UserId, value); }
    
    	private System.DateTime _BorrowDate; //private字段
        public System.DateTime BorrowDate { get => _BorrowDate; set => Set(ref _BorrowDate, value); }
    
    	private Nullable<System.DateTime> _ReturnDate; //private字段
        public Nullable<System.DateTime> ReturnDate { get => _ReturnDate; set => Set(ref _ReturnDate, value); }
    
    	private bool _IsReturn; //private字段
        public bool IsReturn { get => _IsReturn; set => Set(ref _IsReturn, value); }
    
    	private System.DateTime _CreateDateTime; //private字段
        public System.DateTime CreateDateTime { get => _CreateDateTime; set => Set(ref _CreateDateTime, value); }
    
    
        public virtual Tool Tool { get; set; }
        public virtual User User { get; set; }
    }
}
