//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolType : ObservableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolType()
        {
            this.Tools = new List<Tool>();
        }
    
    	private int _id; //private字段
        public int id { get => _id; set => Set(ref _id, value); }
    
    	private string _TypeName; //private字段
        public string TypeName { get => _TypeName; set => Set(ref _TypeName, value); }
    
    	private System.DateTime _CreateDateTime; //private字段
        public System.DateTime CreateDateTime { get => _CreateDateTime; set => Set(ref _CreateDateTime, value); }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tool> Tools { get; set; }
    }
}
