//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolMgt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : ObservableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ToolRecords = new List<ToolRecord>();
        }
    
    	private int _Id; //private字段
        public int Id { get => _Id; set => Set(ref _Id, value); }
    
    	private string _LoginName; //private字段
        public string LoginName { get => _LoginName; set => Set(ref _LoginName, value); }
    
    	private string _RealName; //private字段
        public string RealName { get => _RealName; set => Set(ref _RealName, value); }
    
    	private string _UserID; //private字段
        public string UserID { get => _UserID; set => Set(ref _UserID, value); }
    
    	private int _CompanyID; //private字段
        public int CompanyID { get => _CompanyID; set => Set(ref _CompanyID, value); }
    
    	private string _Password; //private字段
        public string Password { get => _Password; set => Set(ref _Password, value); }
    
    	private byte _Status; //private字段
        public byte Status { get => _Status; set => Set(ref _Status, value); }
    
    	private string _Face; //private字段
        public string Face { get => _Face; set => Set(ref _Face, value); }
    
    	private string _Token; //private字段
        public string Token { get => _Token; set => Set(ref _Token, value); }
    
    	private string _Nfc; //private字段
        public string Nfc { get => _Nfc; set => Set(ref _Nfc, value); }
    
    	private System.DateTime _CreateDateTime; //private字段
        public System.DateTime CreateDateTime { get => _CreateDateTime; set => Set(ref _CreateDateTime, value); }
    
    	private bool _IsDeleted; //private字段
        public bool IsDeleted { get => _IsDeleted; set => Set(ref _IsDeleted, value); }
    
    	private string _UserImg; //private字段
        public string UserImg { get => _UserImg; set => Set(ref _UserImg, value); }
    
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolRecord> ToolRecords { get; set; }
    }
}
